services:
  # 1. Database
  postgres-db: 
    image: postgres:15-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: database_barcode  
      POSTGRES_USER: postgres        
      POSTGRES_PASSWORD: a           
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      app_net:

  # 2. Backend
  backend-app:
    build: ./backend
    container_name: backend_container
    restart: always
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=database_barcode
      - DB_USER=postgres
      - DB_PASS=a
      - DB_PORT=5432
    networks:
      app_net:

  # 3. Frontend
  frontend-app:
    build: ./frontend
    container_name: frontend_container
    restart: always
    networks:
      app_net:

  # 4. Nginx Proxy (Pintu Gerbang Utama)
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "8081:80"   # HTTP lewat 8081 (Biar SCADA 8080 aman)
      - "8443:443"  # HTTPS lewat 8443 (Biar SCADA 443 aman)
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs # Folder sertifikat
    depends_on:
      - frontend-app
      - backend-app
    networks:
      app_net:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiZTJiMzYyZWQwZmU2MzkwNGRlNmNmZjc5NzQ2OGM1YTIiLCJ0IjoiZjU1MDNlMzMtYjcwMS00MzU5LTg2M2ItMTI2YWFlZTVjMzk5IiwicyI6Ik9UbG1ORGRoTldRdE5EazFaaTAwTnpka0xUazJaamd0TXprd1pHUXpOREZrWXprMyJ9
    networks:
      app_net:

      
  # Service Lain (Machine Data & Mosquitto) biarkan seperti semula...
  machine-data:
    build: ./machine_data
    container_name: machine_data_container
    restart: always
    depends_on:
      - postgres-db
      - mosquitto
    environment:
      - MQTT_BROKER=192.168.1.205
      - MQTT_PORT=1883
      - DB_NAME=database_barcode
      - DB_USER=postgres
      - DB_PASS=a
      - DB_HOST=postgres-db
      - DB_PORT=5432
    networks:
      app_net:

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto_broker
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      app_net:
        ipv4_address: 192.168.1.205

volumes:
  pg_data:

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.2/24


