version: '3.8'

services:
  # 1. Database
  postgres-db: 
    image: postgres:15-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: database_barcode  
      POSTGRES_USER: postgres        
      POSTGRES_PASSWORD: a           
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      app_net:

  # 2. Backend
  backend-app:
    build: ./backend
    container_name: backend_container
    restart: always
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=database_barcode
      - DB_USER=postgres
      - DB_PASS=a
      - DB_PORT=5432
    networks:
      app_net:

  # 3. Frontend
  frontend-app:
    build: ./frontend
    container_name: frontend_container
    restart: always
    environment:
      # This grabs DOMAIN_NAME from root .env and injects it into the container
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      app_net:

# 4. Nginx Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "8081:80"   
      - "8443:443"  
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs 
    depends_on:
      - frontend-app
      - backend-app
    networks:
      app_net:

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      app_net:

  # Service Lain
  machine-data:
    build: ./machine_data
    container_name: machine_data_container
    restart: always
    depends_on:
      - postgres-db
      - mosquitto
    environment:
      # INTERNAL: Use the service name "mosquitto"
      - MQTT_BROKER=mosquitto 
      - MQTT_PORT=1883
      - DB_NAME=database_barcode
      - DB_USER=postgres
      - DB_PASS=a
      - DB_HOST=postgres-db
      - DB_PORT=5432
    networks:
      app_net:

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto_broker
    restart: unless-stopped
    ports:
      # EXTERNAL: This maps the container port 1883 to your Armbian IP (192.168.1.205)
      # Any device connecting to 192.168.1.205:1883 will connect here.
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      app_net:

volumes:
  pg_data:

networks:
  app_net:
    driver: bridge
    # We remove custom IPAM/Subnet to let Docker handle internal routing safely.